"""Chat workload driver: replays ShareGPT-format conversations through the proxy.

The point of this driver is not fidelity to human think-time -- it's to put
*chat-shaped* traffic (short context, long unpredictable gaps, exogenous
arrivals) on the same server at the same time as agent traffic, so the two can
be compared, and so heterogeneous-tenancy effects are observable at all.

Per the PRD: fixed inter-turn delay, no think-time distribution model.

Replay semantics: turn k of a conversation re-sends the accumulated history
(human turns 0..k plus the *model's own* generated replies, not the logged
ones). That is what a real chat client does, and it's what makes the prefix
cache do anything.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import sys
import threading
import time
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parents[2]
ROLE_MAP = {"human": "user", "user": "user", "gpt": "assistant",
            "chatgpt": "assistant", "assistant": "assistant", "system": "system"}


def load_conversations(path: Path, limit: int, min_turns: int) -> list[list[dict]]:
    """Accepts ShareGPT ({"conversations":[{"from","value"}]}) or plain
    {"messages":[{"role","content"}]}. Returns lists of user-turn-only prompts;
    assistant turns are regenerated by the model under test."""
    data = json.loads(path.read_text())
    convs: list[list[dict]] = []
    for row in data:
        turns = row.get("conversations") or row.get("items") or row.get("messages") or []
        msgs = []
        for t in turns:
            role = ROLE_MAP.get(str(t.get("from") or t.get("role") or "").lower())
            content = t.get("value") or t.get("content") or ""
            if role and content:
                msgs.append({"role": role, "content": content})
        users = [m for m in msgs if m["role"] == "user"]
        if len(users) >= min_turns:
            convs.append(msgs)
        if 0 < limit <= len(convs):
            break
    return convs


def replay_one(conv_idx: int, msgs: list[dict], args) -> None:
    session_id = f"chat-{conv_idx:05d}"
    base = args.proxy_base_url.rstrip("/")
    url = f"{base}/sess/chat/{session_id}/v1/chat/completions"
    headers = {"X-Session-Id": session_id, "X-Session-Type": "chat",
               "Authorization": f"Bearer {os.environ.get('PROXY_API_KEY', 'dummy')}"}

    history: list[dict] = []
    if msgs and msgs[0]["role"] == "system":
        history.append(msgs[0])

    with httpx.Client(timeout=args.timeout) as client:
        for m in msgs:
            if m["role"] != "user":
                continue
            history.append(m)
            body = {"model": args.model, "messages": history, "stream": True,
                    "max_tokens": args.max_tokens, "temperature": args.temperature}
            reply = ""
            try:
                with client.stream("POST", url, json=body, headers=headers) as r:
                    if r.status_code >= 400:
                        r.read()
                        print(f"[chat] {session_id} http {r.status_code}", file=sys.stderr)
                        return
                    for line in r.iter_lines():
                        if not line.startswith("data: "):
                            continue
                        payload = line[6:].strip()
                        if payload == "[DONE]":
                            break
                        try:
                            obj = json.loads(payload)
                        except json.JSONDecodeError:
                            continue
                        for ch in obj.get("choices") or []:
                            reply += (ch.get("delta") or {}).get("content") or ""
            except httpx.HTTPError as exc:
                print(f"[chat] {session_id} error: {exc}", file=sys.stderr)
                return

            history.append({"role": "assistant", "content": reply})
            time.sleep(args.turn_delay)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--conversations", type=Path,
                    default=ROOT / "data" / "sharegpt.json")
    ap.add_argument("--num-conversations", type=int, default=32)
    ap.add_argument("--concurrency", type=int, default=8)
    ap.add_argument("--min-turns", type=int, default=3)
    ap.add_argument("--turn-delay", type=float, default=2.0,
                    help="fixed inter-turn delay, seconds")
    ap.add_argument("--stagger", type=float, default=0.5,
                    help="delay between session starts, seconds")
    ap.add_argument("--max-tokens", type=int, default=512)
    ap.add_argument("--temperature", type=float, default=0.0)
    ap.add_argument("--timeout", type=float, default=600)
    ap.add_argument("--model", default=os.environ.get("MODEL", "Qwen/Qwen3-8B"))
    ap.add_argument("--proxy-base-url",
                    default=os.environ.get("PROXY_BASE_URL", "http://127.0.0.1:9000"))
    args = ap.parse_args()

    if not args.conversations.exists():
        print(f"no conversation file at {args.conversations} -- "
              f"run drivers/chat_replay/fetch_sharegpt.py first", file=sys.stderr)
        return 2

    convs = load_conversations(args.conversations, args.num_conversations, args.min_turns)
    if not convs:
        print("no conversations met --min-turns", file=sys.stderr)
        return 2
    print(f"[chat] replaying {len(convs)} conversations, concurrency={args.concurrency}")

    sem = threading.Semaphore(args.concurrency)
    rnd = random.Random(0)

    def run(i, msgs):
        with sem:
            replay_one(i, msgs, args)
            print(f"[chat] session chat-{i:05d} done", flush=True)

    threads = []
    for i, msgs in enumerate(convs):
        t = threading.Thread(target=run, args=(i, msgs), daemon=True)
        t.start()
        threads.append(t)
        time.sleep(rnd.uniform(0, args.stagger))  # chat arrivals are exogenous
    for t in threads:
        t.join()
    print("[chat] done")
    return 0


if __name__ == "__main__":
    sys.exit(main())
